services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DevP4ssw0rdOnly!
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      SA_PASSWORD: DevP4ssw0rdOnly!
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'DevP4ssw0rdOnly!' -Q 'SELECT 1' -b -C"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s